from __future__ import annotations
import argparse, json, time
from pathlib import Path
import numpy as np
import torch
from sklearn.preprocessing import StandardScaler
from mf_train_baseline.mf_train import FeatureMLP
from mf_train_baseline.mf_utils import train_feature_mlp, mlp_predict_and_features, train_svgp_per_dim, predict_svgp_per_dim, CsvLogger, rmse, r2_score, set_seed
from .common import load_bundle
from .common import HFPCATransform
def metrics(y,p):
 return {"rmse":float(rmse(y,p)),"r2":float(r2_score(y,p))}
def fit_rho(lf,y,ridge=1e-6):
 mlf=lf.mean(0); my=y.mean(0); lc=lf-mlf; yc=y-my; rho=np.mean(lc*yc,0)/(np.mean(lc*lc,0)+ridge); return rho.astype(np.float32),(my-rho*mlf).astype(np.float32)
def run(a):
 set_seed(a.seed); d=load_bundle(a.data_dir); dev=torch.device(a.device if a.device=='cpu' or torch.cuda.is_available() else 'cpu'); out=Path(a.out_dir).resolve(); out.mkdir(parents=True,exist_ok=True); t_all=time.perf_counter()
 hf,lp,lu=d.hf,d.lf_paired,d.lf_unpaired; xtr=np.concatenate([lp["train"]["x"],lu["train"]["x"]]); ytr=np.concatenate([lp["train"]["y"],lu["train"]["y"]]); xva=lp["val"]["x"]
 fp=HFPCATransform(var_ratio=a.fpca_var_ratio,max_dim=a.fpca_max_dim,dim=a.fpca_dim,ridge=a.fpca_ridge,random_state=a.seed).fit(hf["train"]["y"]); R=fp.effective_dim
 ztr=fp.transform(ytr); zva=fp.transform(lp["val"]["y"]); zte=fp.transform(lp["test"]["y"]); zptr=fp.transform(lp["train"]["y"]); zhf=fp.transform(hf["train"]["y"])
 xs=StandardScaler().fit(xtr); xtrs=xs.transform(xtr).astype(np.float32); xvas=xs.transform(xva).astype(np.float32); zs=fp.scaler_z; Ytr=zhf.astype(np.float32); Zlftr=ztr.astype(np.float32); Zlfptr=zptr.astype(np.float32)
 t=time.perf_counter(); net=FeatureMLP(xtrs.shape[1],R,hidden=tuple(a.hidden),feat_dim=a.feat_dim,act=a.act,dropout=a.dropout,feat_act=a.feat_act,leaky_slope=a.feat_leaky_slope).to(dev); net,log=train_feature_mlp(net,xtrs,Zlftr,xvas,zva.astype(np.float32),lr=a.student_lr,batch_size=a.student_bs,weight_decay=a.student_wd,max_epochs=a.student_epochs,patience=a.student_patience,min_delta=a.student_min_delta,device=dev,print_every=0,eval_sets={"paired_val":(xvas,zva.astype(np.float32))},early_stop_set="paired_val"); stage1=time.perf_counter()-t
 def pred_lat(x): return mlp_predict_and_features(net,xs.transform(x).astype(np.float32),device=dev)[0].astype(np.float32)
 zhat_tr_s=pred_lat(hf["train"]["x"]); zhat_va_s=pred_lat(hf["val"]["x"]); zhat_te_s=pred_lat(hf["test"]["x"]); zhat_tr=zs.inverse_transform(zhat_tr_s).astype(np.float32); zhat_va=zs.inverse_transform(zhat_va_s).astype(np.float32); zhat_te=zs.inverse_transform(zhat_te_s).astype(np.float32)
 latent_val=metrics(zva,zhat_va_s); latent_test=metrics(zte,zhat_te_s)
 # Existing Stage-II: HF x scaler, U=[x, unscaled predicted LF latent], affine rho base, SVGP residual.
 xh=StandardScaler().fit(hf["train"]["x"]); Xtr=xh.transform(hf["train"]["x"]).astype(np.float32); Xva=xh.transform(hf["val"]["x"]).astype(np.float32); Xte=xh.transform(hf["test"]["x"]).astype(np.float32); Utr=np.c_[Xtr,zhat_tr]; Uva=np.c_[Xva,zhat_va]; Ute=np.c_[Xte,zhat_te]; us=StandardScaler().fit(Utr); Utr=us.transform(Utr).astype(np.float32); Uva=us.transform(Uva).astype(np.float32); Ute=us.transform(Ute).astype(np.float32); rho_a,rho_b=fit_rho(Zlfptr,Ytr,a.rho_ridge); base=zhat_tr_s*rho_a+rho_b
 delta=(Ytr-base).astype(np.float32); logger=CsvLogger(out/"stage2_trace.csv",out/"stage2_results.csv"); logger.open(); t=time.perf_counter(); gp=train_svgp_per_dim(Xtr=Utr,Ytr=delta,device=dev,inducing_M=a.svgp_M,steps=a.svgp_steps,lr=a.svgp_lr,ard=True,kernel_struct="full",kernel_name=a.kernel,matern_nu=a.matern_nu,feat_dim=None,print_every=0,tag="direct_latent_delta",csv_logger=logger,csv_run_meta={"run_id":"direct_latent","run_name":a.run_kind,"baseline":"direct_latent","seed":a.seed}); stage2=time.perf_counter()-t; logger.close()
 t=time.perf_counter(); muv,varv=predict_svgp_per_dim(gp,Uva,dev); mut,vart=predict_svgp_per_dim(gp,Ute,dev); muv=(muv+(zhat_va_s*rho_a+rho_b)).astype(np.float32); mut=(mut+(zhat_te_s*rho_a+rho_b)).astype(np.float32); predv=fp.inverse(muv); predt=fp.inverse(mut); inf=time.perf_counter()-t
 assert predv.shape==hf["val"]["y"].shape and predt.shape==hf["test"]["y"].shape; assert np.isfinite(predv).all() and np.isfinite(predt).all() and np.isfinite(zhat_va_s).all() and np.isfinite(zhat_te_s).all(); assert d.wavelengths.shape==(predt.shape[1],) and d.idx_wavelength.shape==(predt.shape[1],)
 pred=out/"pred_arrays"; pred.mkdir(exist_ok=True)
 for n,v in [("val_mean",predv),("test_mean",predt),("val_indices",hf["val"]["idx"]),("test_indices",hf["test"]["idx"]),("wavelengths",d.wavelengths),("idx_wavelength",d.idx_wavelength),("lf_latent_val",zhat_va),("lf_latent_test",zhat_te),("lf_latent_val_scaled",zhat_va_s),("lf_latent_test_scaled",zhat_te_s)]: np.save(pred/f"{n}.npy",v)
 report={"method":"Direct-latent Stage-I ablation","run_kind":a.run_kind,"scientific_result":a.run_kind=="scientific","dataset":a.dataset,"setting":d.root.name,"seed":a.seed,"fpca_effective_dim":R,"stage1_protocol":"x -> z_L directly; z targets use HF-train spectral scaler, HF-train FPCA, HF-train latent scaler","stage2_protocol":"submitted SVGP delta GP with U=[standardized HF x, predicted unscaled z_L], affine rho base fit independently per coordinate on paired LF latent train","stage1_architecture":{"hidden":a.hidden,"feat_dim":a.feat_dim,"activation":a.act,"feat_activation":a.feat_act,"feat_leaky_slope":a.feat_leaky_slope,"dropout":a.dropout,"optimizer":"AdamW","lr":a.student_lr,"batch_size":a.student_bs,"epochs":a.student_epochs,"epochs_ran":log["meta"]["epochs_ran"],"patience":a.student_patience,"weight_decay":a.student_wd,"early_stopping_data":"paired LF validation"},"scaling":{"x":"StandardScaler fit on paired+unpaired LF train","spectral":"HF train only","latent":"HF train FPCA scores only","stage2_x":"HF train only","stage2_u":"HF train only"},"latent_metrics":{"coordinate_space":"HF-train-standardized FPCA coefficients","reference":"paired LF labels projected through the HF-trained representation","val":latent_val,"test":latent_test},"metrics":{"val":metrics(hf["val"]["y"],predv),"test":metrics(hf["test"]["y"],predt)},"timing":{"stage1_train_s":stage1,"stage2_train_s":stage2,"inference_val_test_s":inf,"total_model_wall_s":stage1+stage2+inf},"data_counts":{"hf_train":len(hf["train"]["x"]),"hf_val":len(hf["val"]["x"]),"hf_test":len(hf["test"]["x"]),"lf_train_total":len(xtr)},"comparison_note":"Only the Stage-I target/output changes: direct latent rather than full LF spectrum. Hidden capacity and Stage-II are retained; the output head necessarily has fewer parameters (R rather than 500 outputs)."}
 (out/"report.json").write_text(json.dumps(report,indent=2)); (out/"timing.json").write_text(json.dumps({"method":"Direct-latent Stage-I ablation","dataset":a.dataset,"setting":d.root.name,"seed":a.seed,**report["timing"],"excludes_em_simulation_time":True},indent=2)); print(json.dumps(report,indent=2))
def main():
 p=argparse.ArgumentParser(description="Direct-latent Stage-I ablation"); p.add_argument("--data_dir",required=True); p.add_argument("--out_dir",required=True); p.add_argument("--seed",type=int,default=200); p.add_argument("--dataset",choices=["TM","AB","MTM"],default="TM"); p.add_argument("--device",default="cpu"); p.add_argument("--run_kind",choices=["smoke","scientific"],default="scientific"); p.add_argument("--fpca_var_ratio",type=float,default=.999); p.add_argument("--fpca_max_dim",type=int,default=64); p.add_argument("--fpca_dim",type=int,default=0); p.add_argument("--fpca_ridge",type=float,default=1e-8); p.add_argument("--hidden",type=int,nargs="+",default=[256,256,256]); p.add_argument("--feat_dim",type=int,default=32); p.add_argument("--act",default="relu",choices=["relu","tanh","gelu"]); p.add_argument("--feat_act",default="leakyrelu",choices=["leakyrelu","identity","same"]); p.add_argument("--feat_leaky_slope",type=float,default=.01); p.add_argument("--dropout",type=float,default=0.0); p.add_argument("--student_lr",type=float,default=3e-4); p.add_argument("--student_bs",type=int,default=256); p.add_argument("--student_wd",type=float,default=1e-4); p.add_argument("--student_epochs",type=int,default=2000); p.add_argument("--student_patience",type=int,default=100); p.add_argument("--student_min_delta",type=float,default=1e-4); p.add_argument("--svgp_M",type=int,default=64); p.add_argument("--svgp_steps",type=int,default=2000); p.add_argument("--svgp_lr",type=float,default=5e-3); p.add_argument("--kernel",default="matern",choices=["rbf","matern"]); p.add_argument("--matern_nu",type=float,default=2.5); p.add_argument("--rho_ridge",type=float,default=1e-6); a=p.parse_args(); run(a)
if __name__=='__main__': main()
