#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
plot_efficiency_panels_ab_multi_lfx_clean.py

Clean 2-panel figure (no AR1), split by LF multiplier:
  (a) Equal-accuracy HF-call speedup vs Target test RMSE
  (b) Equal-accuracy wall-clock (simulation-time) speedup vs Target test RMSE

- Plots three curves (lfx=5/10/15).
- Optional compact inset text box summarizing equal-accuracy mapping at ONE representative RMSE point.

Inputs: speedup_curves.npz for each lfx, generated by make_efficiency_speedup_tables.py --curve_lfx {5,10,15}

Outputs:
  efficiency_panels_ab_multi_lfx_clean.png / .pdf

Run (example from project root):
  python plot_efficiency_panels_ab_multi_lfx_clean.py \
    --npz_5  ./.../efficiency_out_lfx05/speedup_curves.npz \
    --npz_10 ./.../efficiency_out_lfx10/speedup_curves.npz \
    --npz_15 ./.../efficiency_out_lfx15/speedup_curves.npz \
    --out_dir ./.../efficiency_out_multi
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, Tuple, List

import numpy as np
import matplotlib.pyplot as plt


def load_npz(p: Path) -> Dict[str, np.ndarray]:
    if not p.exists():
        raise FileNotFoundError(f"NPZ not found: {p.resolve()}")
    d = np.load(p, allow_pickle=True)
    return {k: d[k] for k in d.files}


def finite_xy(x: np.ndarray, y: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    m = np.isfinite(x) & np.isfinite(y)
    return x[m], y[m]


def fmt_hf(x: float) -> str:
    if not np.isfinite(x):
        return "NA"
    return f"{int(round(float(x)))}"


def fmt_hours(sec: float) -> str:
    if not np.isfinite(sec):
        return "NA"
    return f"{float(sec)/3600.0:.2f}"


def choose_representative_index(rmse: np.ndarray, y: np.ndarray, mode: str = "mid") -> int:
    m = np.isfinite(rmse) & np.isfinite(y)
    idx = np.where(m)[0]
    if len(idx) == 0:
        return -1
    r = rmse[idx]
    if mode == "best":
        return int(idx[np.argmin(r)])
    if mode == "worst":
        return int(idx[np.argmax(r)])
    med = np.median(r)
    return int(idx[np.argmin(np.abs(r - med))])

# python plot_efficiency_panels_ab_multi_lfx_clean.py \
#   --npz_5  ./mf_sweep_runs_baseline_trNested_valFresh_devTestFixed_tsmt_s33_500/efficiency_out_lfx05/speedup_curves.npz \
#   --npz_10 ./mf_sweep_runs_baseline_trNested_valFresh_devTestFixed_tsmt_s33_500/efficiency_out_lfx10/speedup_curves.npz \
#   --npz_15 ./mf_sweep_runs_baseline_trNested_valFresh_devTestFixed_tsmt_s33_500/efficiency_out_lfx15/speedup_curves.npz \
#   --out_dir ./mf_sweep_runs_baseline_trNested_valFresh_devTestFixed_tsmt_s33_500/efficiency_out_multi

def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--npz_5", type=str,
                    default="../../result_out/mf_sweep_runs_baseline_nano_tm/efficiency_out_lfx05/speedup_curves.npz")
    ap.add_argument("--npz_10", type=str,
                    default="../../result_out/mf_sweep_runs_baseline_nano_tm/efficiency_out_lfx10/speedup_curves.npz")
    ap.add_argument("--npz_15", type=str,
                    default="../../result_out/mf_sweep_runs_baseline_nano_tm/efficiency_out_lfx15/speedup_curves.npz")
    ap.add_argument("--out_dir", type=str, default="../../result_out/mf_sweep_runs_baseline_nano_tm/efficiency_out_multi")
    ap.add_argument("--xlabel", type=str, default="Target test RMSE")
    ap.add_argument("--x_invert", type=int, default=1)
    ap.add_argument("--dpi", type=int, default=300)
    ap.add_argument("--rep_mode", type=str, default="mid", choices=["mid","best","worst"])
    ap.add_argument("--show_inset", type=int, default=0,
                    help="1: show compact mapping inset (one representative point); 0: no inset.")
    ap.add_argument("--mark_rep_point", type=int, default=1)
    args = ap.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    items: List[Tuple[str, Path]] = []
    if args.npz_5.strip():
        items.append(("lfx=5", Path(args.npz_5)))
    if args.npz_10.strip():
        items.append(("lfx=10", Path(args.npz_10)))
    if args.npz_15.strip():
        items.append(("lfx=15", Path(args.npz_15)))
    if not items:
        raise ValueError("Provide at least one of --npz_5/--npz_10/--npz_15")

    data = [(lab, load_npz(p)) for lab, p in items]

    plt.rcParams.update({
        "font.size": 10,
        "axes.titlesize": 11,
        "axes.labelsize": 10,
        "legend.fontsize": 9,
        "xtick.labelsize": 9,
        "ytick.labelsize": 9,
        "axes.linewidth": 0.9,
        "savefig.bbox": "tight",
    })

    fig = plt.figure(figsize=(7.2, 3.1))
    gs = fig.add_gridspec(1, 2, wspace=0.28)
    axa = fig.add_subplot(gs[0, 0])
    axb = fig.add_subplot(gs[0, 1])

    inset_lines_a: List[str] = []
    inset_lines_b: List[str] = []

    for lab, d in data:
        rmse = d["rmse_targets"].astype(np.float64)

        # (a) HF-call speedup
        s_hf = d.get("hf_speedup_ours_vs_hfonly", None)
        if s_hf is None:
            raise KeyError(f"{lab} missing hf_speedup_ours_vs_hfonly")
        x, y = finite_xy(rmse, s_hf.astype(np.float64))
        axa.plot(x, y, label=lab, linewidth=1.9)

        irep = choose_representative_index(rmse, s_hf.astype(np.float64), mode=args.rep_mode)
        if irep >= 0 and "hfmin_hfonly" in d and "hfmin_ours" in d:
            e = float(rmse[irep])
            hfmin_hfonly = float(d["hfmin_hfonly"][irep])
            hfmin_ours = float(d["hfmin_ours"][irep])
            inset_lines_a.append(f"{lab}: ours {fmt_hf(hfmin_ours)} HF ↔ HF-only {fmt_hf(hfmin_hfonly)} HF @ RMSE={e:.4f}")
            if args.mark_rep_point:
                yy = float(s_hf[irep])
                if np.isfinite(e) and np.isfinite(yy):
                    axa.scatter([e], [yy], s=18)
                    axa.annotate(
                        f"{yy:.2f}×",  # 只标 speedup（最干净）
                        xy=(e, yy),
                        xytext=(-10, 6),  # 右上偏移，避免盖住点
                        textcoords="offset points",
                        ha="left",
                        va="bottom",
                        fontsize=8,
                    )

        # (b) wall-clock speedup
        s_sim = d.get("sim_speedup_ours_vs_hfonly", None)
        if s_sim is not None:
            x2, y2 = finite_xy(rmse, s_sim.astype(np.float64))
            axb.plot(x2, y2, label=lab, linewidth=1.9)

            irep2 = choose_representative_index(rmse, s_sim.astype(np.float64), mode=args.rep_mode)
            if irep2 >= 0 and "time_hfonly_at_target_sec" in d and "time_ours_at_target_sec" in d:
                e2 = float(rmse[irep2])
                t_hfonly = float(d["time_hfonly_at_target_sec"][irep2])
                t_ours = float(d["time_ours_at_target_sec"][irep2])
                inset_lines_b.append(f"{lab}: ours {fmt_hours(t_ours)} h ↔ HF-only {fmt_hours(t_hfonly)} h @ RMSE={e2:.4f}")
                if args.mark_rep_point:
                    yy2 = float(s_sim[irep2])
                    if np.isfinite(e2) and np.isfinite(yy2):
                        axb.scatter([e2], [yy2], s=18)
                        axb.annotate(
                            f"{yy2:.2f}×",
                            xy=(e2, yy2),
                            xytext=(-10, 6),
                            textcoords="offset points",
                            ha="left",
                            va="bottom",
                            fontsize=8,
                        )

    axa.set_title("(a) Equal-accuracy HF-call speedup")
    axb.set_title("(b) Equal-accuracy wall-clock speedup")
    axa.set_xlabel(args.xlabel)
    axb.set_xlabel(args.xlabel)
    axa.set_ylabel("Speedup (×)")
    axb.set_ylabel("Speedup (×)")
    axa.grid(True, alpha=0.3)
    axb.grid(True, alpha=0.3)

    if args.x_invert:
        axa.invert_xaxis()
        axb.invert_xaxis()

    def robust_ylim(ax):
        ys = []
        for line in ax.get_lines():
            y = line.get_ydata()
            y = y[np.isfinite(y)]
            y = y[y > 0]
            if len(y):
                ys.append(y)
        if not ys:
            return
        yall = np.concatenate(ys)
        lo = np.percentile(yall, 2)
        hi = np.percentile(yall, 98)
        if np.isfinite(lo) and np.isfinite(hi) and lo < hi:
            ax.set_ylim(max(1e-3, lo*0.85), hi*1.15)

    robust_ylim(axa)
    robust_ylim(axb)

    handles, labs = axa.get_legend_handles_labels()
    if handles:
        axa.legend(handles, labs, loc="upper left", frameon=False)

    # ---- inset boxes outside axes (below each panel) ----
    if args.show_inset:
        # 给底部留一点空间放 inset（否则可能被 tight bbox 挤掉）
        fig.subplots_adjust(bottom=0.28)

        pa = axa.get_position()  # in figure coordinates
        pb = axb.get_position()

        if inset_lines_a:
            fig.text(
                pa.x0, pa.y0 - 0.08,
                       "Equal-accuracy mapping (HF calls)\n" + "\n".join(inset_lines_a),
                ha="left", va="top", fontsize=8,
                bbox=dict(boxstyle="round,pad=0.25", alpha=0.85),
            )

        if inset_lines_b:
            fig.text(
                pb.x0, pb.y0 - 0.08,
                       "Equal-accuracy mapping (simulation time)\n" + "\n".join(inset_lines_b),
                ha="left", va="top", fontsize=8,
                bbox=dict(boxstyle="round,pad=0.25", alpha=0.85),
            )

    out_png = out_dir / "efficiency_multi_lfx.png"
    out_pdf = out_dir / "efficiency_multi_lfx.pdf"
    fig.savefig(out_png, dpi=int(args.dpi))
    fig.savefig(out_pdf)
    plt.close(fig)

    print(f"[DONE] wrote: {out_png}")
    print(f"[DONE] wrote: {out_pdf}")


if __name__ == "__main__":
    main()
